"""Pydantic params models + SDL entity contracts for Webflow Connector --
core: connection management, Sites, Pages. Domain-specific schemas (CMS,
Assets, Forms, Ecommerce, Webhooks, Comments, Components, Site
Configuration) live in their own schemas_<domain>.py modules, same
convention as Aidentika's schemas_generation.py / schemas_manage.py.

All params models are module-scope (V17 federal invariant, same rule as
MuleSoft Connector / UiPath Connector / Power Automate Connector's
schemas.py).
"""
from __future__ import annotations

from pydantic import BaseModel, Field
from imperal_sdk import sdl


class NoParams(BaseModel):
    """Explicit empty params model -- V17 disallows untyped handlers."""
    pass


# ──────────────────────────────────────────────────────────────────────────
# Connection
# ──────────────────────────────────────────────────────────────────────────


class ConnectWebflowParams(BaseModel):
    site_token: str = Field(
        "",
        description="Site Token generated in Webflow Site Settings > Apps & integrations > API access.",
    )
    label: str = Field("", description="Optional friendly name for this connected site (defaults to the site's own name once verified).")


class ConnectWebflowWorkspaceParams(BaseModel):
    workspace_token: str = Field(
        "",
        description="Workspace Token (read-only, all sites in a Webflow Workspace). Generated by a Workspace admin.",
    )
    label: str = Field("", description="Optional friendly name for this workspace connection.")


class ProviderConnection(sdl.Entity):
    id: str
    title: str
    detail: str = ""
    kind: str = "site"  # "site" | "workspace"


class ProviderConnectionList(sdl.Entity):
    title: str = "Webflow connections"
    items: list[ProviderConnection] = []


class DisconnectWebflowParams(BaseModel):
    connection_id: str = Field(..., description="Connection id from list_connections.")


class DeleteResult(sdl.Entity):
    id: str
    title: str = "Deleted"
    ok: bool = True


# ──────────────────────────────────────────────────────────────────────────
# Sites
# ──────────────────────────────────────────────────────────────────────────


class ListSitesParams(BaseModel):
    connection_id: str = Field("", description="Which connected site/workspace to use. Omit if only one is connected.")


class WebflowSite(sdl.Entity):
    id: str
    display_name: str = ""
    short_name: str = ""
    workspace_id: str = ""
    custom_domains: list[str] = []
    default_domain: str = ""
    time_zone: str = ""
    created_on: str = ""
    last_published: str = ""
    last_updated: str = ""
    parent_folder_id: str = ""


class WebflowSiteList(sdl.Entity):
    title: str = "Sites"
    items: list[WebflowSite] = []


class GetSiteParams(BaseModel):
    connection_id: str = Field("", description="Connection id from list_connections. Omit if only one is connected.")
    site_id: str = Field(..., description="Site id from list_sites.")


class PublishSiteParams(BaseModel):
    connection_id: str = Field("", description="Connection id from list_connections. Omit if only one is connected.")
    site_id: str = Field(..., description="Site id from list_sites.")
    custom_domains: list[str] = Field(default_factory=list, description="Custom domain ids to publish to. Omit to publish to the default webflow.io domain and all previously published custom domains.")
    publish_to_webflow_subdomain: bool = Field(True, description="Also publish to the default *.webflow.io domain.")


class PublishSiteResult(sdl.Entity):
    site_id: str
    queued: bool = True
    title: str = "Publish queued"


# ──────────────────────────────────────────────────────────────────────────
# Pages
# ──────────────────────────────────────────────────────────────────────────


class ListPagesParams(BaseModel):
    connection_id: str = Field("", description="Connection id from list_connections. Omit if only one is connected.")
    site_id: str = Field(..., description="Site id from list_sites.")
    locale_id: str = Field("", description="Optional locale id, for sites with localization enabled.")


class WebflowPage(sdl.Entity):
    id: str
    site_id: str = ""
    title: str = ""
    slug: str = ""
    parent_id: str = ""
    collection_id: str = ""
    is_draft: bool = False
    is_archived: bool = False
    seo_title: str = ""
    seo_description: str = ""
    og_title: str = ""
    og_description: str = ""
    og_image: str = ""
    created_on: str = ""
    last_updated: str = ""
    last_published: str = ""


class WebflowPageList(sdl.Entity):
    title: str = "Pages"
    items: list[WebflowPage] = []


class GetPageParams(BaseModel):
    connection_id: str = Field("", description="Connection id from list_connections. Omit if only one is connected.")
    page_id: str = Field(..., description="Page id from list_pages.")


class UpdatePageMetaParams(BaseModel):
    connection_id: str = Field("", description="Connection id from list_connections. Omit if only one is connected.")
    page_id: str = Field(..., description="Page id from list_pages.")
    title: str = Field("", description="New page title. Omit to leave unchanged.")
    slug: str = Field("", description="New page slug. Omit to leave unchanged.")
    seo_title: str = Field("", description="New SEO meta title. Omit to leave unchanged.")
    seo_description: str = Field("", description="New SEO meta description. Omit to leave unchanged.")
    og_title: str = Field("", description="New Open Graph title. Omit to leave unchanged.")
    og_description: str = Field("", description="New Open Graph description. Omit to leave unchanged.")


class GetPageContentParams(BaseModel):
    connection_id: str = Field("", description="Connection id from list_connections. Omit if only one is connected.")
    page_id: str = Field(..., description="Page id from list_pages.")
    locale_id: str = Field("", description="Optional locale id, for sites with localization enabled.")


class WebflowPageNode(sdl.Entity):
    id: str
    type: str = ""
    tag: str = ""
    text: str = ""


class WebflowPageContent(sdl.Entity):
    page_id: str
    nodes: list[WebflowPageNode] = []


class UpdatePageContentParams(BaseModel):
    connection_id: str = Field("", description="Connection id from list_connections. Omit if only one is connected.")
    page_id: str = Field(..., description="Page id from list_pages.")
    locale_id: str = Field("", description="Optional locale id, for sites with localization enabled.")
    nodes: list[dict] = Field(..., description="Node id -> text/content updates, in Webflow's DOM node update shape (node id, text or component instance props).")


class DuplicatePageParams(BaseModel):
    connection_id: str = Field("", description="Connection id from list_connections. Omit if only one is connected.")
    page_id: str = Field(..., description="Page id to duplicate, from list_pages.")
    label: str = Field("", description="Optional label suffix for the duplicated page's title.")
